// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8pKj1Fsr-4GM4n2zSYu3GI794Q-2rSdE',
    appId: '1:1083523484604:web:8d834bd4984831867af9b9',
    messagingSenderId: '1083523484604',
    projectId: 'umkm-1802b',
    authDomain: 'umkm-1802b.firebaseapp.com',
    storageBucket: 'umkm-1802b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChxVZR95gk9-Ij5Z3FuXkbAEyHAywhShg',
    appId: '1:1083523484604:android:8378f0eeae5842717af9b9',
    messagingSenderId: '1083523484604',
    projectId: 'umkm-1802b',
    storageBucket: 'umkm-1802b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvfjiBSvfbSIh0TguhJ0WtsJGBlPuzQ80',
    appId: '1:1083523484604:ios:93a11e8170d4c4e47af9b9',
    messagingSenderId: '1083523484604',
    projectId: 'umkm-1802b',
    storageBucket: 'umkm-1802b.firebasestorage.app',
    iosClientId: '1083523484604-n0rfmv4snuddujnuas0fna812vls5di1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bangkitUsaha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvfjiBSvfbSIh0TguhJ0WtsJGBlPuzQ80',
    appId: '1:1083523484604:ios:93a11e8170d4c4e47af9b9',
    messagingSenderId: '1083523484604',
    projectId: 'umkm-1802b',
    storageBucket: 'umkm-1802b.firebasestorage.app',
    iosClientId: '1083523484604-n0rfmv4snuddujnuas0fna812vls5di1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bangkitUsaha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8pKj1Fsr-4GM4n2zSYu3GI794Q-2rSdE',
    appId: '1:1083523484604:web:991d33c903dd64607af9b9',
    messagingSenderId: '1083523484604',
    projectId: 'umkm-1802b',
    authDomain: 'umkm-1802b.firebaseapp.com',
    storageBucket: 'umkm-1802b.firebasestorage.app',
  );

}